---



  - name: Install apache2
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"  

  - name: start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"

  - name: enable apache2 service
    service:
      name: apache2
      enabled: yes
    when: ansible_distribution == "Ubuntu"
  

  - name: Install httpd
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "CentOS"

  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"
  
  - name: enable httpd service
    service:
      name: httpd
      enabled: yes
    when: ansible_distribution == "CentOS"
...