---



  - name: Install apache2
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debain" 

  - name: start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debain"

  - name: enable apache2 service
    service:
      name: apache2
      enabled: yes
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debain"
  

  - name: Install httpd
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"
  
  - name: enable httpd service
    service:
      name: httpd
      enabled: yes
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon" 
...