---
- name: update node1 server
  hosts: node1
  remote_user: root

  tasks:
  - name: create a directory
    file:
      path: /home/centos/node1_directory
      state: directory

- name: update node2 server
  hosts: node2
  remote_user: root

  tasks:
  - name: create a directory
    file:
      path: /home/centos/node2_directory
      state: directory
      
- name: update group of server
  hosts: g1
  remote_user: root

  tasks:
  - name: create a directory on g1
    file:
      path: /home/centos/new_dir
      state: directory

  - name: create a directory on g1
    file:
      path: /home/centos/new_dir-1
      state: directory
...