---
- name: Install apache2 on ubuntu server
  hosts: node2
  become: yes

  tasks:
  - name: Install apache2
    apt:
      name: apache2
      state: present

  - name: start apache2 service
    service:
      name: apache2
      state: started

  - name: enable apache2 service
    service:
      name: apache2
      enabled: yes
...