---
- name: Install apache on amazon & ubuntu server
  hosts: g1
  become: yes

  tasks:
  - name: Install apache2
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"  

  - name: start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"

  - name: enable apache2 service
    service:
      name: apache2
      enabled: yes
    when: ansible_distribution == "Ubuntu"
  
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "centos"

  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_distribution == "centos"
  - name: enable httpd service
    service:
      name: httpd
      enabled: yes
    when: ansible_distribution == "centos"
...