---
# tasks file for html
- name: Install git
    yum:
      name: git
      state: present


- name: Get files from git hub
    git:
      repo: https://github.com/ravi2krishna/ecomm.git
      dest: /var/www/html
      force: yes
  